#!/usr/bin/env bash
#
# https://github.com/railwaycat/homebrew-emacsmacport
#
# brew tap railwaycat/emacsmacport
# brew install emacs-mac
ARGV=$*
EMACS="$HOME/.local/opt/emacs-mac/Emacs.app"

open $EMACS $ARGV
